Create entry point
tarikbouari/School-library-app pull request #4
Opened 2022-11-12 16:45 UTC by tarikbouari

In this milestone I implement the following action:

- Create class app
- List all books.
- List all people.
- Create a person (teacher or student, not a plain Person).
- Create a book.
- Create a rental.
- List all rentals for a given person id.
- Create the app entry point in the main.rb file 
- Refactor code and fix linters errors

2022-11-12 17:16 UTC, alexander16108 requested changes
Hi @tarikbouari , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/VwwKdq5NV0nwQ/giphy.gif"/>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 17:16 UTC, alexander16108 commented on app.rb
> +end
you have an issue when creating a person `teacher`  currently it shows this error

![image](https://user-images.githubusercontent.com/60612329/201486152-451a27f1-204b-416d-9c6f-8b4e7e583804.png)

2022-11-12 17:16 UTC, alexander16108 commented on app.rb
> +end
you have an issue when creating a rental currently your app shows these errors

![image](https://user-images.githubusercontent.com/60612329/201486283-267d0ff3-4b86-46df-a486-97778b86f163.png)

2022-11-12 19:21 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @tarikbouari👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 19:21 UTC, thecodechaser commented on app.rb
> +end
- [ ] When I'm trying to list rentals for a person, I get nothing on the screen. Please fix this issue.

![image](https://user-images.githubusercontent.com/83803414/201491098-518bf5e9-232f-4cdf-a1cd-5b3e0e185962.png)

2022-11-17 13:15 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @tarikbouari, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

✔️ No linter error.
✔️ Proper Gitflow used.
✔️ Descriptive PR title & description.
✔️ Descriptive readme file.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 13:22 UTC, merged